export const CONTACT= 'Contacts'
export const CONTACT_DETAIL = 'Contact Details'
export const CREATE_CONTACT = 'Create Contact'
export const SETTINGS = 'Settings'
export const LOGIN = 'Login'
export const REGISTER = 'Register'
export const HOME_NAVIGATORS = 'Home'